### ISSUE TITLE
RuntimeError: Can not execute clone Ubuntu 13

### ISSUE THREAD

**Issue by haradreborn** [Friz-zy/pyspaces#1]
After `pip install pyspaces`

`adminuser@adminuser-VirtualBox:~/git/_test$ space chroot --pid --uid '0 1000 1' ~/.local/share/lxc/ubuntu/rootfs/ /bin/ls /home/`

`Traceback (most recent call last):
  File "/usr/local/bin/space", line 9, in <module>
    load_entry_point('pyspaces==1.2.2', 'console_scripts', 'space')()
  File "/usr/local/lib/python2.7/dist-packages/pyspaces/cli.py", line 99, in cli
    args.func(args, extra)
  File "/usr/local/lib/python2.7/dist-packages/pyspaces/cli.py", line 142, in chroot
    c.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/local/lib/python2.7/dist-packages/pyspaces/cloning.py", line 102, in __init__
    'Can not execute clone'
RuntimeError: Can not execute clone`

**Comment by Friz-zy** [comment]
Hello,
First of all, thanks for your feedback!

Unprivileged processes can create namespaces [since 3.8 Linux](http://man7.org/linux/man-pages/man7/user_namespaces.7.html), but Stéphane Graber [recommended](https://www.stgraber.org/2014/01/17/lxc-1-0-unprivileged-containers/) use Ubuntu 14.04 and latest for unprivileged containers:

> All examples and instructions I’ll be giving below are expecting that you are running a perfectly up to date version of Ubuntu 14.04 (codename trusty).
> The reason to want something that recent is because the rough requirements for well working unprivileged containers are:
>     1) Kernel: 3.13 + a couple of staging patches (which Ubuntu has in its kernel)
>     2) User namespaces enabled in the kernel
>     3) A very recent version of shadow that supports subuid/subgid
>     4) Per-user cgroups on all controllers (which I turned on a couple of weeks ago)
>     5) LXC 1.0 beta2 or higher (released two days ago)
>     6) A version of PAM with a loginuid patch that’s yet to be in any released version

So, you can try use next fixes:
- execute space from root or sudo
- update your virtual ubuntu at least to 14.04
- update kernel in your ubuntu 13

Otherwise it'll not work as you expect.

**Comment by haradreborn** [comment]
Sorry, forgot about kernel version requirement. Works great on 14.04. Thanks
